logging:
  wandb_log: True
  wandb_project: "SuperTinyLanguageModels"

paths:
  output_dir: "outputs"
  data_dir: "../scratchDirectory/STLMData"
  checkpoint_dir: "checkpoints"

seed: 489
device: cuda
