core_model_type: "generic"
hidden_dim: 128
depth: 8
num_heads: 8
ffn_dim: 512
bias: False
# modern version e.g.
attn_type: "rope"
attn_group_size: 2
ffn_type: "kan"
ffn_activation: "gelu"
normalization: "rmsnorm"
