model:
  k_interior_layers: 1
  lora_rank: 64
  checkpoint_path: Null
  core_model:
    core_model_type: ffn_lora_sharing_moe
    num_layers: 6
    ffn:
      ffn_type: swiglu
      ffn_dim: 1072
      normalization: rms_norm
      bias: false
      lora_rank: 32
      n_experts: 8
      lora_alpha: 1.0
    attn:
      attn_type: generic
      num_heads: 16
      normalization: rms_norm
      group_size: 4
      bias: false
      is_causal: true
  embedder:
    tokenizer_type: bpe-retrain
    embedding_model_type: generic
    dataset_name: en_wiki
  lm_head:
    normalization: rms_norm
    bias: false
    lm_head_type: generic
  hidden_dim: 416
  context_window: 512
  vocab_size: 4000
  model_shell_type: standard
  embedding_weight_tying: true
  positional_encoding_type: rope
trainer:
  dropout_scheduler:
    dropout_type: constant
    dropout: 0.0
  dataset: simple_en_wiki
  training:
    trainer_type: base_trainer
    batch_size: 2
    gradient_accumulation_steps: 20
    max_iters: 80000
    lr_decay_iters: 80000
    warmup_iters: 10000
    eval_interval: 2000
    log_interval: 10
    eval_iters: 500
    checkpoint_interval: 10000.0
    run_profiler: false
  eval:
    - benchmarks:
        - "winograd"
        - "hellaswag"
        - "arc"
        - "mmlu"
        - "blimp"
      num_samples: 1000
      evaluator: "mcq"
    - evaluator: "prog"
  optimizer:
    name: nanoGPTadamW
    lr: 0.0006
    min_lr: 6.0e-05
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.95
    grad_clip: 1.0
    decay_lr: true
    warmup_iters: 10000
  lr_scheduler:
    name: cosine
  dataloader:
    name: standard
  datasampling:
    name: standard
  loss_fn:
    name: cross_entropy
general:
  logging:
    wandb_log: false
    wandb_project: SuperTinyLanguageModels
  paths:
    output_dir: outputs
    data_dir: data
    checkpoint_dir: checkpoints
    eval_dir: evals
  seed: 489
  device: cpu
