model:
  core_model:
    core_model_type: passthrough
  embedder:
    tokenizer_type: "gpt2"
    byte_tokenizer_type: "bpe"
    embedding_model_type: byte_level
    byte_context_window: 12
    dataset_name: simple_en_wiki
  lm_head:
    normalization: rms_norm
    bias: false
    lm_head_type: byte_level

  hidden_dim: 768
  context_window: 512
  vocab_size: 50257
  byte_vocab_size: 258
  byte_context_window: 12
  byte_embedding_dim: 128
  model_shell_type: byte_shell
  embedding_weight_tying: false
  positional_encoding_type: rope
trainer:
  dropout_scheduler:
    dropout_type: constant
    dropout: 0.1
    start_dropout_p: 0.0
    end_dropout_p: 0.1
    start_iter: 0
    end_iter: 10000
  dataset: simple_en_wiki
  training:
    trainer_type: base_trainer
    batch_size: 16
    gradient_accumulation_steps: 30
    max_iters: 50000
    lr_decay_iters: 50000
    warmup_iters: 5000
    eval_interval: 500
    log_interval: 100
    eval_iters: 200
    checkpoint_interval: 1000000000.0
    run_profiler: false
  optimizer:
    name: adamW
    lr: 0.0006
    min_lr: 6.0e-05
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.99
    grad_clip: 1.0
    decay_lr: true
    warmup_iters: 5000
  lr_scheduler:
    name: cosine
  dataloader:
    name: dual_byte_pooling
  datasampling:
    name: standard
  loss_fn:
    name: cross_entropy
  eval:

general:
  logging:
    wandb_log: true
    wandb_project: SuperTinyLanguageModels
  paths:
    output_dir: outputs
    data_dir: data
    checkpoint_dir: checkpoints
  seed: 489
  device: cpu
