defaults:
- core_model: baseline
- embedder: baseline
- lm_head: baseline

hidden_dim: 512
context_window: 512
vocab_size: 50257
model_shell_type: "standard"
embedding_weight_tying: True
positional_encoding_type: "rope"