generator_type: adaptive_sampler
# temperature: 1.2
# top_k: 200
max_new_tokens: 200
beam_width: 15
use_sampling: true
repetition_penalty: 1.2
repetition_window: 32
input_text: "Let's consider a simple Python program that adds two integers."

temperature: 0.666
top_p: 0.90
top_k: 27
min_p: 0.03  # Turn this down to 0.01 to reduce the shoggoth

low_ent_thresh: 0.1
low_vent_thresh: 0.1
med_ent_thresh: 3.0
high_ent_thresh: 5.0
high_vent_thresh: 5.0

# TODO this is a bit of a nasty mess, but also makes all the hyperparameters visible
helv_attn_ent_offset: 1.3
helv_attn_ent_coef: 0.2

lehv_interaction_strength_offset: 1.2
lehv_interaction_strength_coef: 0.3

hehv_attn_ent_coef: 0.2
hehv_attn_vent_offset: 2.0
hehv_attn_vent_coef: 0.5

# TODO not convinced this should
n_adaptive_samples: 5

# Adaptive sampling parameters
ada_temp_logits: 0.3
ada_temp_attn: 0.2
ada_temp_agree: 0.2
ada_top_p: 0.1
ada_top_k_int: 0.3
ada_top_k_agree: 0.2
ada_min_p: 0.5
ada_score_logits_ent: 0.1
ada_score_attn_ent: 0.2
ada_score_logits_vent: 0.3
ada_score_attn_vent: 0.4
ada_score_agree: 0.5
ada_score_int: 0.6