defaults:
  - _self_
  - train: baseline
benchmarks:
  - "arc"
  - "hellaswag"
  - "mmlu"
  # - "mteb"
  - "nonsense"
  - "vitaminc"
  - "winograd"
generate_config:
  max_new_tokens: 4
  temperature: 0.4
  top_k: 10
checkpoint_path: "outputs/2024-04-05/14-15-43/checkpoints/ckpt_10000.pt"