defaults:
  # - testing: "llm_harness"
  - testing: "baseline"
#model_ckpt: "checkpoints/..."
model:
  model_string: "openai-community/gpt2"
  flash_attention: false
  core_model:
    core_model_type: hf_core
  embedder:
    embedding_model_type: hf_embedder
    tokenizer_type: hf_tokenizer
    dataset_name: simple_en_wiki
  lm_head:
    lm_head_type: hf_head
  hidden_dim: 3072
  context_window: 512
  vocab_size: 32064
  model_shell_type: standard
  embedding_weight_tying: false
  positional_encoding_type: rope
generate_config:
  temperature: 0.8
  top_k: 10
output_path: "results.json"
