model:
  core_model_type: generic
  num_layers: 5
  
  ffn:
    ffn_type: generic
    ffn_dim: 1536
    activation: gelu
    normalization: rms_norm
    bias: false
    dropout: 0.0

  attn:
    attn_type: rope_attention
    num_kv_heads: 4
    num_q_heads: 8 # has to be == num_kv_heads for alibi attention
    normalization: rms_norm
    bias: false
    dropout: false

  embedding_model_type: generic
  tokenizer_type: bpe
  tokenizer_dataset_names: [simple_en_wiki]
  tokenizer_simplify_data: true
  vocab_size: 4000

  hidden_dim: 384
  context_window: 2048

  lm_head_type: generic
  lm_head_normalization: rms_norm
  lm_head_bias: false
  lm_head_dropout: 0.0

  model_shell_type: standard
  embedding_weight_tying: true
  ffn_weight_tying: false
  cproj_weight_tying: false
  positional_encoding_type: rope

trainer:
  trainer_type: base_trainer
  dataset: fineweb_edu_10B
  batch_size: 24
  gradient_accumulation_steps: 10

  max_iters: 50000
  eval_interval: 5000
  log_interval: 10
  checkpoint_interval: 10000
  eval_iters: 1000

  eval:
    benchmarks:
      - Ewok-Subset
      - Blimp-Subset
      - Teacher-Text-Modeling (full)
      - Text-Generation (full)
      - STLM-Text-Modeling (full)
    val_loss_iters: 1000

  optimizer:
    optimizer_name: adamW
    lr: 5.0e-4
    min_lr: 5.0e-5
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.98
    grad_clip: 1.0

  lr_scheduler:
    name: cosine
    warmup_iters: 2500

  dataloader:
    name: standard

  datasampling:
    name: standard

  loss_fn:
    name: cross_entropy

general:
  logging:
    wandb_log: true
    wandb_project: SuperTinyLanguageModels
    wandb_run_name: Null
    group_name: base_group

  paths:
    output_dir: outputs
    data_dir: data
    checkpoint_dir: checkpoints
    eval_dir: evals
  seed: 489
  device: cuda
