wandb_run_name: "thinking"
defaults:
  - baseline
arch:
  model: "thinking"
  gamma: 0.9
  confidence_threshold: 0.05

training:
  dataset: "en_wiki"
  iterations: 1
  gradient_accumulation_steps: 20
